version: '3'

services:

  laravel-workerman:
    # image: nginx:1.18
    build:
      context: .
    container_name: laravel-workerman
    restart: always
    # ports:
    #   - 8080:8080
    working_dir: /var/www
    labels:
      - "traefik.http.routers.laravel-workerman.rule=Host(`laraworkman.local.com`)"
      - "traefik.http.services.laravel-workerman.loadbalancer.server.port=23460"
    volumes:
      - .:/var/www
    networks:
      - web_service
    command: "tail -f /dev/null"

  laravel-workerman-db:
    image: mariadb:10.5.6
    container_name: laravel-workerman-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # DB 密碼
      MYSQL_DATABASE: laravel
    networks:
      - web_service

networks:
  web_service:
    external: true